// const mongoose = require("mongoose");

// const categorySchema = new mongoose.Schema(
//   {
//     name: {
//       type: String,
//       // enum: [
//       //   "Toys and Games",
//       //   "Kitchen, Cookware & Serveware",
//       //   "Pens & Stationery",
//       //   "Health Care",
//       //   "Wearable Smart Devices",
//       //   "Exercise & Fitness",
//       //   "Home Improvement",
//       //   "Food Products",
//       //   "Bags, Wallets & Belts",
//       //   "Watches",
//       //   "Pet Supplies",
//       //   "Kids Accessories",
//       //   "Home Decor",
//       //   "Vehicles",
//       //   "Festive Decor & Gifting",
//       //   "Sports",
//       //   "Footwear",
//       //   "Clothing and Accessories",
//       //   "Automotive Accessories",
//       //   "Industrial & Scientific Supplies",
//       //   "Building Materials and Supplies",
//       //   "Beauty and Grooming",
//       //   "Mobiles & Accessories",
//       //   "Computers",
//       //   "Cameras & Accessories",
//       //   "Gaming",
//       //   "Home Entertainment",
//       //   "Home & Kitchen",
//       //   "Home Lighting",
//       //   "Jewellery",
//       //   "Home Cleaning & Bathroom Accessories",
//       //   "Audio & Video",
//       //   "Vas",
//       //   "Home Furnishing",
//       //   "Furniture",
//       //   "Sunglasses",
//       //   "Health & Personal Care Appliances",
//       //   "Baby Care",
//       //   "Toys",
//       // ],
//       required: true,
//     },
//     group: {
//       type: String,
//       enum: [
//         "For You",
//         "Fashion",
//         "Mobiles",
//         "Beauty",
//         "Electronics",
//         "Home",
//         "Appliances",
//         "Toys",
//         "Food",
//         "Sports",
//       ],
//       required: true,
//     },
//     icon: {
//       type: String,
//       required: true,
//     },
//     // parentCategory: {
//     //   type: mongoose.Schema.Types.ObjectId,
//     //   ref: "Category",
//     //   default: null,
//     // },
//   },
//   { timestamps: true },
// );

// module.exports = mongoose.model("Category", categorySchema);
